/* Catálogos de la plataforma de solicitudes de movimientos (los mismos de la versión probada).
   Generado desde solicitudes-movimientos/Code.gs del repositorio privado; para cambiar un catálogo edítalo aquí. */
export const AREAS = ["Customer Service","Mercadotecnia","Ventas","Calidad","Distribución","Almacén / CEDIS","Logística","Compras","Producción","Dirección","Otra área"];
export const TIPOS = [["devolucion","Devolución de cliente","Material que regresa un cliente. Pide fotos y checklist."],["recoleccion","Recolección","Exhibidores, mesas o material en un punto."],["envio","Envío o entrega","Llevar producto, muestras o material a un destino."],["traslado","Traslado entre plantas o bodegas","Planta, CEDIS, bodegas o sucursales."],["mercadotecnia","Mercadotecnia","Stands, exhibidores y eventos."],["renta","Renta de unidad","Unidad dedicada por días o semanas."],["maniobras","Maniobras","Carga, descarga o acomodo de material."],["otro","Otro","Cualquier otro movimiento de logística."]];
export const ESTADOS = {"recibida":"Recibida","en_revision":"En revisión","informacion":"Falta información","programada":"Programada","en_transito":"En tránsito","completada":"Completada","cancelada":"Cancelada","rechazada":"No procede"};
export const ABIERTOS = ["recibida","en_revision","informacion","programada","en_transito"];
export const CANCELABLES = ["recibida","en_revision","informacion"];
export const FORMAS_ENVIO = ["Camión / unidad","Paquetería","Que lo decida Logística"];
export const PAQUETERIA = "Paquetería";
export const FACTOR_VOLUMETRICO = 5000;
export const MOTIVOS_DEVOLUCION = ["Cambio de tono","Cambio de calibre","Cambio de formato","Producto dañado","Producto equivocado","Producto incompleto","Sobrante de obra","El cliente ya no lo requiere","Otro"];
export const CHECKLIST_DEVOLUCION = ["Está en su empaque original y las cajas están cerradas","Las cajas no tienen golpes ni humedad, y no hay piezas rotas o despostilladas","No ha sido instalado, cortado ni manipulado","Las etiquetas (lote, tono y calibre) se ven y coinciden con lo facturado","La cantidad coincide con la factura o la nota de crédito","Está en tarima, flejado y emplayado, listo para cargar","La devolución está autorizada (nota de crédito o autorización del gerente)"];
export const CATEGORIAS = ["EXTERNO","ALMACEN","OBRA","PAQUETERIA","OTROS"];
export const TRANSPORTISTAS = ["ACARREOS MAMAEV","ALMEX","AM INTERMODAL","AUTOEXPRESS AGUILAR","AUTOEXPRESS CARRASCO","AUTOEXPRESS CERVANTES","AUTOEXPRESS DEL MINERAL","AUTOEXPRESS ESTRADA","AUTOEXPRESS MEDINA","AUTOEXPRESS MUÑOZ","AUTOEXPRESS OLIVAS","AUTOEXPRESS PARGA","AUTOEXPRESS POTRILLOS","AUTOEXPRESS VELAZQUEZ","AUTOTRANSPORTES HERIVA","CH ROBINSON","CLIENTE ENVIA UNIDAD","DANIEL FERNANDEZ","DESARROLLO LOGISTICO","FEMA","FRANCISCO ORTEGA","GROMAR","JOEL MARTINEZ","LOGISTICA INTERNACIONAL","MASER","MATA TRUCKING","OSVALDO ORTIZ","OVERSEAS","PALOS GARZA","PAQUETEEXPRESS","PAQUETERIA","ROJAS","SOLISTICA","TARKUS TRANSPORTES","TRANSPORTE BISONTE","TRANSPORTES 3H","TRANSPORTES ACUÑA","TRANSPORTES ARANCETION","TRANSPORTES AURORA ESQUIVEL","TRANSPORTES CARMONA","TRANSPORTES CARVAN","TRANSPORTES DOMINGUEZ","TRANSPORTES ELEAM","TRANSPORTES GUTIERREZ","TRANSPORTES HEFL","TRANSPORTES J HERNANDEZ","TRANSPORTES JASA","TRANSPORTES LEXA","TRANSPORTES LINARES","TRANSPORTES LOPEZ INTERNACIONAL","TRANSPORTES LOZAGUI","TRANSPORTES MAROLOS","TRANSPORTES MARTINEZ GUTIERREZ","TRANSPORTES NAVARRO","TRANSPORTES PINEDO","TRANSPORTES SALAS","TRANSPORTES SIFUENTES","TRANSPORTES TEEXSA","TRANSPORTES TNT","TRANSPORTES TORRES","TRANSPORTES TRAZA","TRANSPORTES TREJOS TRUCKING","TRANSPORTES VATRU","TRUCKA","UBER FREIGHT"];
export const TIPOS_UNIDAD = ["SENCILLO","TORTON","RABON","CAMIONETA 3.5","CAJA SECA 53","CAJA SECA 48","CAJA CERRADA","FULL","PLATAFORMA SENCILLO","PLATAFORMA FULL","CONTENEDOR 20","PAQUETERIA"];
export const CAMPOS = [["solicitante","Nombre",true,120],["area","Área",true,60],["correo","Correo",true,160],["telefono","Teléfono o extensión",true,40],["autoriza","Autoriza",false,120],["tipo","Tipo de movimiento",true,30],["prioridad","Prioridad",true,10],["forma_envio","Forma de envío",true,30],["horario","Horario en sitio",false,80],["cliente","Cliente relacionado",false,160],["referencia","Pedido, factura o RMA",false,120],["motivo","Motivo y detalles",true,2000],["dev_motivo","Motivo de la devolución",false,60],["dev_checklist","Puntos que cumple el material",false,1500],["origen_nombre","Origen",true,160],["origen_direccion","Dirección de origen",true,240],["origen_ciudad","Ciudad de origen",true,120],["origen_contacto","Contacto en origen",false,160],["destino_nombre","Destino",true,160],["destino_direccion","Dirección de destino",true,240],["destino_ciudad","Ciudad de destino",true,120],["destino_contacto","Contacto en destino",false,160]];
export const CAMPOS_LOGISTICA = ["folio_cstext","categorizacion","responsable","transportista","unidad_asignada","guia","fecha_programada","notas_internas"];
